sudo: required
language: generic

services:
  - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

branches:
  except:
    - /^debian\/\d/

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "I Sagar"
      - git config --local user.email "i.vikram15@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: 
    secure: "HejaovUhX2pUFb+R3WueSrq6j5ECFe/aBCKfDleFRN7jAHzNq8/KnibGndAbsRMiaCQBNZn4iY+GUPqiFZJUhPPyGkI3NRG3XkuPn6YBjsYm/BcJNcobT9eWjSMCaw3nuM8Rh1U4+qSxw/NIPXx+1vsPEl4U8jbYOMkTxYDPp04qopgAILdapSrN9pYuI/uFAL75XD6tlV+a/mxReC9ae56SJSkNsnWKB6q26Jlek7HZp41qmlbHMGMKFvMpt00m8mwN/KyXvgWrirYCS+hZDwwOC7LZfeCh72wo9URie1+3R5SGgfSUf9+1fBsTjJrNP40pqXKcWEJrdEJapSLkQQ95sBI+MS0WgezCs7b/SM2btjWuPPHl/a3XbZX1QshS0vlymzjiffYoJxbqTbFB1qiDEc4Iob/RE+MtsxUsBGlikom8A2ubHc78p5HnjJOQHtGQLFg+fjHPSV8EHU1LkId/Q1mxgWTBNcRjAmVJBVXbyk41anHVxLZUOB82xsKzDconoOnpRkpdB9DgL49Ef6jY5cXaY9V7Lz9lZIl6xYop11zUgipJeWGr+0IFPNnFsfbXcmk+Bnb9H6zo+GjjIgvbXb8WaWSTa1w9VpLX0wUG03dd85O7Gn60BS1uc45afkgVKJ77ad6RmOE1WkZgX3P8Cqx7x+3uc59hIUuaBVg="
  file_glob: true
  file: ../*.deb
  skip_cleanup: true
