sudo: required
language: generic

services:
  - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

branches:
  except:
    - /^debian\/\d/

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "I Sagar"
      - git config --local user.email "i.vikram15@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: 
    secure: "cObAleRdPZJTqnmIzvjv+BbNUig1WgfstlwWBUdbpJeICdKPTXVuFbs868Mp+N2CqbzZsehIIpeQQvaSZTVuEaUGDXaC1EIIDNyDTfvU8lbcnR27ho92U1oItAtvr90J+6fgZ7HJE2bZGMzI6F4BRjkp+tbcCKFgFdrfVBl6IQ1f16Ep3ULUWfYxi+tmfH0iNFnnXuJsjuOgHi7UTQxj24uJomCFMmY7qNYcT4c1Qj8w9ExBinjb/XkUUtzL/q1iBhXVpkmmvBbHJlk0Arc0e8bthOiK5HVpDeknseg9XFHkcOXelzrLktDp22wcHHB+jEDbXLqeqt0IG+XND251d6dCKlg92MDI9l4QbR3gPxfD6PwvIsmTfCNqP13rKix3MkELfuXLz+xAYssmK3JcrRYrfABa/zLd8huMXnt5rLcoeN6QLsML3bE1hCVArkHMjtz5W47B84atpV5ZECfIDKNG8xlKdSsXQ1WuMdb+kzqamM/RkXDX7tuvD0cRNSkj/bIKMkw1sw9YPJ/199BSfw2v9RE5+gfnwz54NfRCepBE6lQDLdzCGBZtQUU8aEEg63Vc6hnKNCY+NegRyozIJm+TEmWROp5ZIxD19IzeOOAoALuR9H1IYPu0JFUIj8QgSB3rggOdAwBsRO/tZG4Bhlrh5g5vtiZ8BDjCiv12hgY="
  file_glob: true
  file: ../*.deb
  skip_cleanup: true
